CREATE TABLE properties (
    id SERIAL PRIMARY KEY,
    nombre_alias VARCHAR(255) NOT NULL,
    cedula_habitabilidad VARCHAR(50),
    licencia_turistica VARCHAR(50),
    direccion_completa TEXT NOT NULL,
    tipo_propiedad VARCHAR(50) NOT NULL,
    capacidad_maxima INTEGER NOT NULL,
    numero_habitaciones INTEGER,
    numero_banos INTEGER,
    metros_cuadrados INTEGER,
    descripcion_corta TEXT,
    amenidades TEXT,
    codigo_airbnb VARCHAR(50),
    url_airbnb TEXT,
    codigo_booking VARCHAR(50),
    url_booking TEXT,
    precio_base_noches DECIMAL(10,2),
    ibi_anual DECIMAL(10,2),
    gastos_comunidad DECIMAL(10,2),
    hipoteca_mensual DECIMAL(10,2),
    coste_limpieza DECIMAL(10,2),
    contacto_propietario_nombre VARCHAR(255),
    contacto_propietario_telefono VARCHAR(20),
    contacto_propietario_email VARCHAR(255),
    limpiador_nombre VARCHAR(255),
    limpiador_telefono VARCHAR(20),
    fontanero_nombre VARCHAR(255),
    fontanero_telefono VARCHAR(20),
    seguro_hogar_aseguradora VARCHAR(255),
    seguro_hogar_poliza VARCHAR(50),
    seguro_hogar_fecha_venc DATE,
    seguro_hogar_telefono VARCHAR(20),
    seguro_hogar_email VARCHAR(255),
    seguro_rc_aseguradora VARCHAR(255),
    seguro_rc_poliza VARCHAR(50),
    seguro_rc_fecha_venc DATE,
    seguro_rc_telefono VARCHAR(20),
    seguro_rc_email VARCHAR(255),
    contrato_electricidad_empresa VARCHAR(255),
    contrato_electricidad_contrato VARCHAR(50),
    contrato_electricidad_fecha_venc DATE,
    contrato_electricidad_telefono VARCHAR(20),
    contrato_agua_empresa VARCHAR(255),
    contrato_agua_contrato VARCHAR(50),
    contrato_agua_fecha_venc DATE,
    contrato_agua_telefono VARCHAR(20),
    contrato_internet_empresa VARCHAR(255),
    contrato_internet_contrato VARCHAR(50),
    contrato_internet_fecha_venc DATE,
    contrato_internet_telefono VARCHAR(20),
    contrato_gas_empresa VARCHAR(255),
    contrato_gas_contrato VARCHAR(50),
    contrato_gas_fecha_venc DATE,
    contrato_gas_telefono VARCHAR(20),
    foto_url TEXT,
    notas_adicionales TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
