package scripts

import (
	"database/sql"
	"log"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/jgargallo/property-manager/models"
)

// SeedPropertiesHandler clears all properties and inserts 5 dummy properties with contract info.
// func SeedPropertiesHandler(db *sql.DB, service *models.PropertyService) http.HandlerFunc {
// 	return func(w http.ResponseWriter, r *http.Request) {
// 		// Delete all properties
// 		_, err := db.Exec("DELETE FROM properties")
// 		if err != nil {
// 			http.Error(w, "Error clearing properties: "+err.Error(), http.StatusInternalServerError)
// 			return
// 		}

// 		// Dummy properties with contract info
// 		props := []models.Property{
// 			{
// 				NombreAlias:       "Casa Sol",
// 				DireccionCompleta: "Calle Sol 1, Madrid",
// 				TipoPropiedad:     "Apartamento",
// 				CapacidadMaxima:   4,
// 				CreatedAt:         time.Now(),
// 				UpdatedAt:         time.Now(),
// 				ContactoPropietario: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Juan Pérez", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Propietario", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "600111222", Valid: true},
// 					Email:          sql.NullString{String: "juan@sol.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Juan Pérez", Valid: true},
// 				},
// 				Limpiador: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Limpiezas Sol", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(0, 6, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "600333444", Valid: true},
// 					Email:          sql.NullString{String: "info@limpiezassol.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Ana López", Valid: true},
// 				},
// 				Fontanero: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Fontanería Madrid", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Servicio anual", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "600555666", Valid: true},
// 					Email:          sql.NullString{String: "contacto@fontaneriamadrid.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Pedro Fonta", Valid: true},
// 				},
// 				SeguroHogar: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Seguros Sol", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Poliza 12345", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900111222", Valid: true},
// 					Email:          sql.NullString{String: "hogar@segurossol.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Laura Segura", Valid: true},
// 				},
// 				SeguroRc: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Seguros RC", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Poliza RC-9876", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900333444", Valid: true},
// 					Email:          sql.NullString{String: "rc@segurosrc.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Carlos Ruiz", Valid: true},
// 				},
// 				ContratoElectricidad: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Iberdrola", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato E-2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900123456", Valid: true},
// 					Email:          sql.NullString{String: "info@iberdrola.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Miguel Luz", Valid: true},
// 				},
// 				ContratoAgua: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Canal Isabel II", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato Agua 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900654321", Valid: true},
// 					Email:          sql.NullString{String: "contacto@canalisabelii.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Sara Canal", Valid: true},
// 				},
// 				ContratoInternet: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Movistar", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato Fibra 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900789012", Valid: true},
// 					Email:          sql.NullString{String: "soporte@movistar.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Luis Red", Valid: true},
// 				},
// 				ContratoGas: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Naturgy", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato Gas 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900321654", Valid: true},
// 					Email:          sql.NullString{String: "info@naturgy.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Eva Gas", Valid: true},
// 				},
// 			},
// 			{
// 				NombreAlias:       "Villa Luna",
// 				DireccionCompleta: "Avenida Luna 22, Barcelona",
// 				TipoPropiedad:     "Villa",
// 				CapacidadMaxima:   8,
// 				CreatedAt:         time.Now(),
// 				UpdatedAt:         time.Now(),
// 				ContactoPropietario: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Pedro Luna", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Propietario", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "600222333", Valid: true},
// 					Email:          sql.NullString{String: "pedro@luna.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Pedro Luna", Valid: true},
// 				},
// 				Limpiador: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Limpiezas Luna", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(0, 6, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "600444555", Valid: true},
// 					Email:          sql.NullString{String: "info@limpiezasluna.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Mario Luna", Valid: true},
// 				},
// 				Fontanero: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Fontanería BCN", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Servicio anual", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "600666777", Valid: true},
// 					Email:          sql.NullString{String: "contacto@fontaneriabcn.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Berta Fonta", Valid: true},
// 				},
// 				SeguroHogar: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Seguros Luna", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Poliza 54321", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900222333", Valid: true},
// 					Email:          sql.NullString{String: "hogar@segurosluna.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Luna Segura", Valid: true},
// 				},
// 				SeguroRc: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Seguros RC Luna", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Poliza RC-1234", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900444555", Valid: true},
// 					Email:          sql.NullString{String: "rc@segurosrcluna.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Luna Ruiz", Valid: true},
// 				},
// 				ContratoElectricidad: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Endesa", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato E-2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900654987", Valid: true},
// 					Email:          sql.NullString{String: "info@endesa.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Luna Luz", Valid: true},
// 				},
// 				ContratoAgua: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Aigües de Barcelona", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato Agua 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900987654", Valid: true},
// 					Email:          sql.NullString{String: "contacto@aiguesbcn.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Luna Canal", Valid: true},
// 				},
// 				ContratoInternet: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Orange", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato Fibra 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900888999", Valid: true},
// 					Email:          sql.NullString{String: "soporte@orange.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Luna Red", Valid: true},
// 				},
// 				ContratoGas: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Gas Natural", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato Gas 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900111999", Valid: true},
// 					Email:          sql.NullString{String: "info@gasnatural.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Luna Gas", Valid: true},
// 				},
// 			},
// 			{
// 				NombreAlias:       "Estudio Mar",
// 				DireccionCompleta: "Paseo Marítimo 5, Valencia",
// 				TipoPropiedad:     "Estudio",
// 				CapacidadMaxima:   2,
// 				CreatedAt:         time.Now(),
// 				UpdatedAt:         time.Now(),
// 				ContactoPropietario: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "María Mar", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Propietario", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "600333444", Valid: true},
// 					Email:          sql.NullString{String: "maria@mar.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "María Mar", Valid: true},
// 				},
// 				Limpiador: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Limpiezas Mar", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(0, 6, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "600555666", Valid: true},
// 					Email:          sql.NullString{String: "info@limpiezasmar.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Marina Mar", Valid: true},
// 				},
// 				Fontanero: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Fontanería Valencia", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Servicio anual", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "600777888", Valid: true},
// 					Email:          sql.NullString{String: "contacto@fontaneriavalencia.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Valen Fonta", Valid: true},
// 				},
// 				SeguroHogar: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Seguros Mar", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Poliza 67890", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900333444", Valid: true},
// 					Email:          sql.NullString{String: "hogar@segurosmar.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Mar Segura", Valid: true},
// 				},
// 				SeguroRc: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Seguros RC Mar", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Poliza RC-5678", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900555666", Valid: true},
// 					Email:          sql.NullString{String: "rc@segurosrcmar.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Mar Ruiz", Valid: true},
// 				},
// 				ContratoElectricidad: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Iberdrola", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato E-2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900123456", Valid: true},
// 					Email:          sql.NullString{String: "info@iberdrola.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Mar Luz", Valid: true},
// 				},
// 				ContratoAgua: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Aguas Valencia", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato Agua 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900654321", Valid: true},
// 					Email:          sql.NullString{String: "contacto@aguasvalencia.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Mar Canal", Valid: true},
// 				},
// 				ContratoInternet: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Vodafone", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato Fibra 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900789012", Valid: true},
// 					Email:          sql.NullString{String: "soporte@vodafone.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Mar Red", Valid: true},
// 				},
// 				ContratoGas: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Naturgy", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato Gas 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900321654", Valid: true},
// 					Email:          sql.NullString{String: "info@naturgy.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Mar Gas", Valid: true},
// 				},
// 			},
// 			{
// 				NombreAlias:       "Ático Centro",
// 				DireccionCompleta: "Plaza Mayor 10, Sevilla",
// 				TipoPropiedad:     "Ático",
// 				CapacidadMaxima:   3,
// 				CreatedAt:         time.Now(),
// 				UpdatedAt:         time.Now(),
// 				ContactoPropietario: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Antonio Centro", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Propietario", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "600444555", Valid: true},
// 					Email:          sql.NullString{String: "antonio@centro.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Antonio Centro", Valid: true},
// 				},
// 				Limpiador: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Limpiezas Centro", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(0, 6, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "600666777", Valid: true},
// 					Email:          sql.NullString{String: "info@limpiezascentro.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Carmen Centro", Valid: true},
// 				},
// 				Fontanero: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Fontanería Sevilla", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Servicio anual", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "600888999", Valid: true},
// 					Email:          sql.NullString{String: "contacto@fontaneriasevilla.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Sevi Fonta", Valid: true},
// 				},
// 				SeguroHogar: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Seguros Centro", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Poliza 11223", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900444555", Valid: true},
// 					Email:          sql.NullString{String: "hogar@seguroscentro.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Centro Segura", Valid: true},
// 				},
// 				SeguroRc: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Seguros RC Centro", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Poliza RC-4321", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900666777", Valid: true},
// 					Email:          sql.NullString{String: "rc@segurosrccentro.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Centro Ruiz", Valid: true},
// 				},
// 				ContratoElectricidad: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Endesa", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato E-2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900654987", Valid: true},
// 					Email:          sql.NullString{String: "info@endesa.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Centro Luz", Valid: true},
// 				},
// 				ContratoAgua: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Emasesa", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato Agua 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900987654", Valid: true},
// 					Email:          sql.NullString{String: "contacto@emasesa.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Centro Canal", Valid: true},
// 				},
// 				ContratoInternet: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Orange", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato Fibra 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900888999", Valid: true},
// 					Email:          sql.NullString{String: "soporte@orange.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Centro Red", Valid: true},
// 				},
// 				ContratoGas: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Gas Natural", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato Gas 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900111999", Valid: true},
// 					Email:          sql.NullString{String: "info@gasnatural.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Centro Gas", Valid: true},
// 				},
// 			},
// 			{
// 				NombreAlias:       "Chalet Verde",
// 				DireccionCompleta: "Camino Verde 99, Bilbao",
// 				TipoPropiedad:     "Chalet",
// 				CapacidadMaxima:   6,
// 				CreatedAt:         time.Now(),
// 				UpdatedAt:         time.Now(),
// 				ContactoPropietario: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Verde Propietario", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Propietario", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "600555666", Valid: true},
// 					Email:          sql.NullString{String: "verde@chalet.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Verde Propietario", Valid: true},
// 				},
// 				Limpiador: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Limpiezas Verde", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(0, 6, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "600777888", Valid: true},
// 					Email:          sql.NullString{String: "info@limpiezasverde.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Verde Limpio", Valid: true},
// 				},
// 				Fontanero: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Fontanería Bilbao", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Servicio anual", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "600999000", Valid: true},
// 					Email:          sql.NullString{String: "contacto@fontaneriabilbao.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Bilbao Fonta", Valid: true},
// 				},
// 				SeguroHogar: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Seguros Verde", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Poliza 24680", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900555666", Valid: true},
// 					Email:          sql.NullString{String: "hogar@segurosverde.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Verde Segura", Valid: true},
// 				},
// 				SeguroRc: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Seguros RC Verde", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Poliza RC-2468", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900777888", Valid: true},
// 					Email:          sql.NullString{String: "rc@segurosrcverde.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Verde Ruiz", Valid: true},
// 				},
// 				ContratoElectricidad: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Iberdrola", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato E-2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900123456", Valid: true},
// 					Email:          sql.NullString{String: "info@iberdrola.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Verde Luz", Valid: true},
// 				},
// 				ContratoAgua: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Aguas Bilbao", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato Agua 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900654321", Valid: true},
// 					Email:          sql.NullString{String: "contacto@aguasbilbao.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Verde Canal", Valid: true},
// 				},
// 				ContratoInternet: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Euskaltel", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato Fibra 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900789012", Valid: true},
// 					Email:          sql.NullString{String: "soporte@euskaltel.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Verde Red", Valid: true},
// 				},
// 				ContratoGas: models.ContractInfo{
// 					Empresa:        sql.NullString{String: "Naturgy", Valid: true},
// 					ContratoPoliza: sql.NullString{String: "Contrato Gas 2024", Valid: true},
// 					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
// 					Telefono:       sql.NullString{String: "900321654", Valid: true},
// 					Email:          sql.NullString{String: "info@naturgy.com", Valid: true},
// 					ContactPerson:  sql.NullString{String: "Verde Gas", Valid: true},
// 				},
// 			},
// 		}

// 		// Insert dummy properties
// 		for _, p := range props {
// 			if err := service.CreateProperty(&p); err != nil {
// 				log.Printf("Error inserting property: %v", err)
// 			}
// 		}

// 		w.WriteHeader(http.StatusOK)
// 		w.Write([]byte("Database seeded with 5 dummy properties including contract info."))
// 	}
// }

// Añade este handler para Fiber:
func SeedPropertiesFiberHandler(db *sql.DB, service *models.PropertyService) fiber.Handler {
	return func(c *fiber.Ctx) error {
		_, err := db.Exec("DELETE FROM properties")
		if err != nil {
			return c.Status(500).SendString("Error clearing properties: " + err.Error())
		}

		// Dummy properties with contract info
		props := []models.Property{
			{
				NombreAlias:       "Casa Sol",
				DireccionCompleta: "Calle Sol 1, Madrid",
				TipoPropiedad:     "Apartamento",
				CapacidadMaxima:   4,
				CreatedAt:         time.Now(),
				UpdatedAt:         time.Now(),
				ContactoPropietario: models.ContractInfo{
					Empresa:        sql.NullString{String: "Juan Pérez", Valid: true},
					ContratoPoliza: sql.NullString{String: "Propietario", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "600111222", Valid: true},
					Email:          sql.NullString{String: "juan@sol.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Juan Pérez", Valid: true},
				},
				Limpiador: models.ContractInfo{
					Empresa:        sql.NullString{String: "Limpiezas Sol", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(0, 6, 0), Valid: true},
					Telefono:       sql.NullString{String: "600333444", Valid: true},
					Email:          sql.NullString{String: "info@limpiezassol.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Ana López", Valid: true},
				},
				Fontanero: models.ContractInfo{
					Empresa:        sql.NullString{String: "Fontanería Madrid", Valid: true},
					ContratoPoliza: sql.NullString{String: "Servicio anual", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "600555666", Valid: true},
					Email:          sql.NullString{String: "contacto@fontaneriamadrid.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Pedro Fonta", Valid: true},
				},
				SeguroHogar: models.ContractInfo{
					Empresa:        sql.NullString{String: "Seguros Sol", Valid: true},
					ContratoPoliza: sql.NullString{String: "Poliza 12345", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900111222", Valid: true},
					Email:          sql.NullString{String: "hogar@segurossol.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Laura Segura", Valid: true},
				},
				SeguroRc: models.ContractInfo{
					Empresa:        sql.NullString{String: "Seguros RC", Valid: true},
					ContratoPoliza: sql.NullString{String: "Poliza RC-9876", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900333444", Valid: true},
					Email:          sql.NullString{String: "rc@segurosrc.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Carlos Ruiz", Valid: true},
				},
				ContratoElectricidad: models.ContractInfo{
					Empresa:        sql.NullString{String: "Iberdrola", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato E-2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900123456", Valid: true},
					Email:          sql.NullString{String: "info@iberdrola.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Miguel Luz", Valid: true},
				},
				ContratoAgua: models.ContractInfo{
					Empresa:        sql.NullString{String: "Canal Isabel II", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato Agua 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900654321", Valid: true},
					Email:          sql.NullString{String: "contacto@canalisabelii.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Sara Canal", Valid: true},
				},
				ContratoInternet: models.ContractInfo{
					Empresa:        sql.NullString{String: "Movistar", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato Fibra 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900789012", Valid: true},
					Email:          sql.NullString{String: "soporte@movistar.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Luis Red", Valid: true},
				},
				ContratoGas: models.ContractInfo{
					Empresa:        sql.NullString{String: "Naturgy", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato Gas 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900321654", Valid: true},
					Email:          sql.NullString{String: "info@naturgy.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Eva Gas", Valid: true},
				},
			},
			{
				NombreAlias:       "Villa Luna",
				DireccionCompleta: "Avenida Luna 22, Barcelona",
				TipoPropiedad:     "Villa",
				CapacidadMaxima:   8,
				CreatedAt:         time.Now(),
				UpdatedAt:         time.Now(),
				ContactoPropietario: models.ContractInfo{
					Empresa:        sql.NullString{String: "Pedro Luna", Valid: true},
					ContratoPoliza: sql.NullString{String: "Propietario", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "600222333", Valid: true},
					Email:          sql.NullString{String: "pedro@luna.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Pedro Luna", Valid: true},
				},
				Limpiador: models.ContractInfo{
					Empresa:        sql.NullString{String: "Limpiezas Luna", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(0, 6, 0), Valid: true},
					Telefono:       sql.NullString{String: "600444555", Valid: true},
					Email:          sql.NullString{String: "info@limpiezasluna.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Mario Luna", Valid: true},
				},
				Fontanero: models.ContractInfo{
					Empresa:        sql.NullString{String: "Fontanería BCN", Valid: true},
					ContratoPoliza: sql.NullString{String: "Servicio anual", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "600666777", Valid: true},
					Email:          sql.NullString{String: "contacto@fontaneriabcn.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Berta Fonta", Valid: true},
				},
				SeguroHogar: models.ContractInfo{
					Empresa:        sql.NullString{String: "Seguros Luna", Valid: true},
					ContratoPoliza: sql.NullString{String: "Poliza 54321", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900222333", Valid: true},
					Email:          sql.NullString{String: "hogar@segurosluna.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Luna Segura", Valid: true},
				},
				SeguroRc: models.ContractInfo{
					Empresa:        sql.NullString{String: "Seguros RC Luna", Valid: true},
					ContratoPoliza: sql.NullString{String: "Poliza RC-1234", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900444555", Valid: true},
					Email:          sql.NullString{String: "rc@segurosrcluna.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Luna Ruiz", Valid: true},
				},
				ContratoElectricidad: models.ContractInfo{
					Empresa:        sql.NullString{String: "Endesa", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato E-2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900654987", Valid: true},
					Email:          sql.NullString{String: "info@endesa.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Luna Luz", Valid: true},
				},
				ContratoAgua: models.ContractInfo{
					Empresa:        sql.NullString{String: "Aigües de Barcelona", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato Agua 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900987654", Valid: true},
					Email:          sql.NullString{String: "contacto@aiguesbcn.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Luna Canal", Valid: true},
				},
				ContratoInternet: models.ContractInfo{
					Empresa:        sql.NullString{String: "Orange", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato Fibra 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900888999", Valid: true},
					Email:          sql.NullString{String: "soporte@orange.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Luna Red", Valid: true},
				},
				ContratoGas: models.ContractInfo{
					Empresa:        sql.NullString{String: "Gas Natural", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato Gas 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900111999", Valid: true},
					Email:          sql.NullString{String: "info@gasnatural.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Luna Gas", Valid: true},
				},
			},
			{
				NombreAlias:       "Estudio Mar",
				DireccionCompleta: "Paseo Marítimo 5, Valencia",
				TipoPropiedad:     "Estudio",
				CapacidadMaxima:   2,
				CreatedAt:         time.Now(),
				UpdatedAt:         time.Now(),
				ContactoPropietario: models.ContractInfo{
					Empresa:        sql.NullString{String: "María Mar", Valid: true},
					ContratoPoliza: sql.NullString{String: "Propietario", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "600333444", Valid: true},
					Email:          sql.NullString{String: "maria@mar.com", Valid: true},
					ContactPerson:  sql.NullString{String: "María Mar", Valid: true},
				},
				Limpiador: models.ContractInfo{
					Empresa:        sql.NullString{String: "Limpiezas Mar", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(0, 6, 0), Valid: true},
					Telefono:       sql.NullString{String: "600555666", Valid: true},
					Email:          sql.NullString{String: "info@limpiezasmar.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Marina Mar", Valid: true},
				},
				Fontanero: models.ContractInfo{
					Empresa:        sql.NullString{String: "Fontanería Valencia", Valid: true},
					ContratoPoliza: sql.NullString{String: "Servicio anual", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "600777888", Valid: true},
					Email:          sql.NullString{String: "contacto@fontaneriavalencia.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Valen Fonta", Valid: true},
				},
				SeguroHogar: models.ContractInfo{
					Empresa:        sql.NullString{String: "Seguros Mar", Valid: true},
					ContratoPoliza: sql.NullString{String: "Poliza 67890", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900333444", Valid: true},
					Email:          sql.NullString{String: "hogar@segurosmar.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Mar Segura", Valid: true},
				},
				SeguroRc: models.ContractInfo{
					Empresa:        sql.NullString{String: "Seguros RC Mar", Valid: true},
					ContratoPoliza: sql.NullString{String: "Poliza RC-5678", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900555666", Valid: true},
					Email:          sql.NullString{String: "rc@segurosrcmar.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Mar Ruiz", Valid: true},
				},
				ContratoElectricidad: models.ContractInfo{
					Empresa:        sql.NullString{String: "Iberdrola", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato E-2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900123456", Valid: true},
					Email:          sql.NullString{String: "info@iberdrola.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Mar Luz", Valid: true},
				},
				ContratoAgua: models.ContractInfo{
					Empresa:        sql.NullString{String: "Aguas Valencia", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato Agua 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900654321", Valid: true},
					Email:          sql.NullString{String: "contacto@aguasvalencia.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Mar Canal", Valid: true},
				},
				ContratoInternet: models.ContractInfo{
					Empresa:        sql.NullString{String: "Vodafone", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato Fibra 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900789012", Valid: true},
					Email:          sql.NullString{String: "soporte@vodafone.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Mar Red", Valid: true},
				},
				ContratoGas: models.ContractInfo{
					Empresa:        sql.NullString{String: "Naturgy", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato Gas 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900321654", Valid: true},
					Email:          sql.NullString{String: "info@naturgy.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Mar Gas", Valid: true},
				},
			},
			{
				NombreAlias:       "Ático Centro",
				DireccionCompleta: "Plaza Mayor 10, Sevilla",
				TipoPropiedad:     "Ático",
				CapacidadMaxima:   3,
				CreatedAt:         time.Now(),
				UpdatedAt:         time.Now(),
				ContactoPropietario: models.ContractInfo{
					Empresa:        sql.NullString{String: "Antonio Centro", Valid: true},
					ContratoPoliza: sql.NullString{String: "Propietario", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "600444555", Valid: true},
					Email:          sql.NullString{String: "antonio@centro.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Antonio Centro", Valid: true},
				},
				Limpiador: models.ContractInfo{
					Empresa:        sql.NullString{String: "Limpiezas Centro", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(0, 6, 0), Valid: true},
					Telefono:       sql.NullString{String: "600666777", Valid: true},
					Email:          sql.NullString{String: "info@limpiezascentro.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Carmen Centro", Valid: true},
				},
				Fontanero: models.ContractInfo{
					Empresa:        sql.NullString{String: "Fontanería Sevilla", Valid: true},
					ContratoPoliza: sql.NullString{String: "Servicio anual", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "600888999", Valid: true},
					Email:          sql.NullString{String: "contacto@fontaneriasevilla.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Sevi Fonta", Valid: true},
				},
				SeguroHogar: models.ContractInfo{
					Empresa:        sql.NullString{String: "Seguros Centro", Valid: true},
					ContratoPoliza: sql.NullString{String: "Poliza 11223", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900444555", Valid: true},
					Email:          sql.NullString{String: "hogar@seguroscentro.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Centro Segura", Valid: true},
				},
				SeguroRc: models.ContractInfo{
					Empresa:        sql.NullString{String: "Seguros RC Centro", Valid: true},
					ContratoPoliza: sql.NullString{String: "Poliza RC-4321", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900666777", Valid: true},
					Email:          sql.NullString{String: "rc@segurosrccentro.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Centro Ruiz", Valid: true},
				},
				ContratoElectricidad: models.ContractInfo{
					Empresa:        sql.NullString{String: "Endesa", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato E-2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900654987", Valid: true},
					Email:          sql.NullString{String: "info@endesa.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Centro Luz", Valid: true},
				},
				ContratoAgua: models.ContractInfo{
					Empresa:        sql.NullString{String: "Emasesa", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato Agua 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900987654", Valid: true},
					Email:          sql.NullString{String: "contacto@emasesa.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Centro Canal", Valid: true},
				},
				ContratoInternet: models.ContractInfo{
					Empresa:        sql.NullString{String: "Orange", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato Fibra 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900888999", Valid: true},
					Email:          sql.NullString{String: "soporte@orange.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Centro Red", Valid: true},
				},
				ContratoGas: models.ContractInfo{
					Empresa:        sql.NullString{String: "Gas Natural", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato Gas 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900111999", Valid: true},
					Email:          sql.NullString{String: "info@gasnatural.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Centro Gas", Valid: true},
				},
			},
			{
				NombreAlias:       "Chalet Verde",
				DireccionCompleta: "Camino Verde 99, Bilbao",
				TipoPropiedad:     "Chalet",
				CapacidadMaxima:   6,
				CreatedAt:         time.Now(),
				UpdatedAt:         time.Now(),
				ContactoPropietario: models.ContractInfo{
					Empresa:        sql.NullString{String: "Verde Propietario", Valid: true},
					ContratoPoliza: sql.NullString{String: "Propietario", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "600555666", Valid: true},
					Email:          sql.NullString{String: "verde@chalet.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Verde Propietario", Valid: true},
				},
				Limpiador: models.ContractInfo{
					Empresa:        sql.NullString{String: "Limpiezas Verde", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(0, 6, 0), Valid: true},
					Telefono:       sql.NullString{String: "600777888", Valid: true},
					Email:          sql.NullString{String: "info@limpiezasverde.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Verde Limpio", Valid: true},
				},
				Fontanero: models.ContractInfo{
					Empresa:        sql.NullString{String: "Fontanería Bilbao", Valid: true},
					ContratoPoliza: sql.NullString{String: "Servicio anual", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "600999000", Valid: true},
					Email:          sql.NullString{String: "contacto@fontaneriabilbao.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Bilbao Fonta", Valid: true},
				},
				SeguroHogar: models.ContractInfo{
					Empresa:        sql.NullString{String: "Seguros Verde", Valid: true},
					ContratoPoliza: sql.NullString{String: "Poliza 24680", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900555666", Valid: true},
					Email:          sql.NullString{String: "hogar@segurosverde.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Verde Segura", Valid: true},
				},
				SeguroRc: models.ContractInfo{
					Empresa:        sql.NullString{String: "Seguros RC Verde", Valid: true},
					ContratoPoliza: sql.NullString{String: "Poliza RC-2468", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900777888", Valid: true},
					Email:          sql.NullString{String: "rc@segurosrcverde.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Verde Ruiz", Valid: true},
				},
				ContratoElectricidad: models.ContractInfo{
					Empresa:        sql.NullString{String: "Iberdrola", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato E-2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900123456", Valid: true},
					Email:          sql.NullString{String: "info@iberdrola.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Verde Luz", Valid: true},
				},
				ContratoAgua: models.ContractInfo{
					Empresa:        sql.NullString{String: "Aguas Bilbao", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato Agua 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900654321", Valid: true},
					Email:          sql.NullString{String: "contacto@aguasbilbao.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Verde Canal", Valid: true},
				},
				ContratoInternet: models.ContractInfo{
					Empresa:        sql.NullString{String: "Euskaltel", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato Fibra 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(1, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900789012", Valid: true},
					Email:          sql.NullString{String: "soporte@euskaltel.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Verde Red", Valid: true},
				},
				ContratoGas: models.ContractInfo{
					Empresa:        sql.NullString{String: "Naturgy", Valid: true},
					ContratoPoliza: sql.NullString{String: "Contrato Gas 2024", Valid: true},
					FechaVenc:      sql.NullTime{Time: time.Now().AddDate(2, 0, 0), Valid: true},
					Telefono:       sql.NullString{String: "900321654", Valid: true},
					Email:          sql.NullString{String: "info@naturgy.com", Valid: true},
					ContactPerson:  sql.NullString{String: "Verde Gas", Valid: true},
				},
			},
		}

		// Insert dummy properties
		for _, p := range props {
			if err := service.CreateProperty(&p); err != nil {
				log.Printf("Error inserting property: %v", err)
			}
		}

		c.Status(200).SendString("Base de datos sembrada con 5 propiedades dummy incluyendo información de contratos.")
		return nil
	}
}
